# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

trigger: none # disable triggers based on commits.
pr: none # disable as a PR gate.
name: 'PowerShellExamplesImport Check'
schedules:
  - cron: "0 3 * * FRI"  # every Friday at 3AM UTC (off hours for Redmond, Nairobi and Montréal)
    displayName: 'PowerShellExamplesImport Check'
    branches:
      include:
      - powershell-reference-docs-examples-update
    always: true
parameters:
- name: PipelineTimeout
  displayName: PipelineTimeout
  type: number
  default: 1200
- name: BuildAgent
  displayName: Build Agent
  default: 1es-windows-ps-compute

resources:
 repositories:     
   - repository: msgraph-sdk-powershell
     type: github
     endpoint: microsoftgraph
     name: microsoftgraph/msgraph-sdk-powershell
     ref: powershell-reference-docs-examples-update

jobs:
- job: PowerShellExamplesImport_V2
  pool: 
    name: ${{ parameters.BuildAgent }}
  timeoutInMinutes: ${{ parameters.PipelineTimeout }}
  steps:
  - task: PowerShell@2
    name: "ComputeBranch"
    displayName: "Compute weekly examples update branch name"
    inputs:
      targetType: inline
      script: |
        $branch = "{0}/{1}" -f "WeeklyExamplesUpdate", (Get-Date -Format yyyyMMddHHmm)
        Write-Host "Compute branch: $branch"
        Write-Host "##vso[task.setvariable variable=WeeklyExamplesBranch;isOutput=true]$branch"

  - task: Bash@3
    displayName: "Create weekly examples branch"
    inputs:
      targetType: inline
      script: |
        git status
        git branch $(ComputeBranch.WeeklyExamplesBranch)
        git checkout $(ComputeBranch.WeeklyExamplesBranch)
        git status

  - task: PowerShell@2
    displayName: 'Import Examples From API Reference Docs'
    continueOnError: false
    inputs:
      targetType: 'filePath'
      pwsh: true
      filePath: tools\ExamplesGenerator.ps1

  - task: PowerShell@2
    displayName: Pushing to github
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
    inputs:
      targetType: inline
      pwsh: true
      script: |
        git status
        git add .
        git commit -m "Importing examples"
        git push --set-upstream origin $(ComputeBranch.WeeklyExamplesBranch)
        git status

  # - template: ./common-templates/create-pr.yml
  #   parameters:
  #     BaseBranch: "features/2.0"
  #     TargetBranch: $(ComputeBranch.WeeklyExamplesBranch)
  #     Title: "[v2] Examples Import"
  #     Body: "This pull request was automatically created by Azure Pipelines. **Important** Check for unexpected deletions or changes in this PR."